/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;

public class AppTest {
    @Test public void reaLines() {
        App classUnderTest = new App();
        assert(classUnderTest.readLines("/home/timon/Public/advent-of-code/2024/day_2/example.txt").size() > 0);
    }

    @Test public void lineOnlyIncrease(){
        App classUnderTest = new App();
        String lineUnderTest = "1 3 6 7 9";
        boolean isIncrease = classUnderTest.isIncrease(lineUnderTest);
        assertEquals(isIncrease, true);
    }

    @Test public void lineNotIncrease(){
        App classUnderTest = new App();
        String lineUnderTest = "1 3 6 7 2";
        boolean isIncrease = classUnderTest.isIncrease(lineUnderTest);
        assertEquals(isIncrease, false);
    }

    @Test public void isCleanIncrease(){
        App classUnderTest = new App();
        String lineUnderTest = "1 2 7 8 9";
        boolean isIncrease = classUnderTest.isIncrease(lineUnderTest);
        assertEquals(isIncrease, false);
    }
    @Test public void isCleanDecrease(){
        App classUnderTest = new App();
        String lineUnderTest = "7 6 4 2 1";
        boolean isDecrease = classUnderTest.isDecrease(lineUnderTest);
        assertEquals(isDecrease, true);
    }
    @Test public void isNotCleanDecrease(){
        App classUnderTest = new App();
        String lineUnderTest = "8 6 4 4 1";
        boolean isDecrease = classUnderTest.isDecrease(lineUnderTest);
        assertEquals(isDecrease, false);
    }

    @Test public void isNotSave(){
        App classUnderTest = new App();
        String lineUnderTest = "1 3 2 4 5";
        boolean notSave = classUnderTest.isSafe(lineUnderTest);
        assertEquals(notSave, false);
    }

    @Test public void isSave(){
        App classUnderTest = new App();
        String lineUnderTest = "1 3 6 7 9";
        boolean save = classUnderTest.isSafe(lineUnderTest);
        assertEquals(save, true);
    }

    @Test public void exampleResultCorrect(){
      App classUnderTest = new App();
      List<String> lines = classUnderTest.readLines("/home/timon/Public/advent-of-code/2024/day_2/input.txt");
      int safeResult = 0;
      for (String line : lines){
        if (classUnderTest.isSafe(line))  {
          safeResult += 1;
        }
      }
      assertEquals(safeResult, 2);
    
    }
    


}
