/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.HashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.text.html.HTMLDocument.Iterator;

import java.util.ArrayList;

public class App {
  public List<String> readLines(String path) {
    List<String> allLines = new ArrayList<String>();
    try {
      allLines = Files.readAllLines(Paths.get(path));
    } catch (IOException e) {
      e.printStackTrace();
    }
    return allLines;
  }

  public HashMap<Integer, HashMap<String, List<Integer>>> buildMap(List<String> data) {
    HashMap<Integer, HashMap<String, List<Integer>>> result = new HashMap<Integer, HashMap<String, List<Integer>>>();
    Pattern patternA = Pattern.compile("Button A: X\\+\\d+, Y\\+\\d+", Pattern.CASE_INSENSITIVE);
    Pattern patternB = Pattern.compile("Button B: X\\+\\d+, Y\\+\\d+", Pattern.CASE_INSENSITIVE);
    Pattern patPrize = Pattern.compile("X=\\d+, Y=\\d+", Pattern.CASE_INSENSITIVE);
    Pattern digit = Pattern.compile("\\d+");

    Integer i = 0;

    for (String line : data) {
      HashMap<String, List<Integer>> small = new HashMap<String, List<Integer>>();
      Matcher matcherA = patternA.matcher(line);
      Matcher matcherB = patternB.matcher(line);
      Matcher prize = patPrize.matcher(line);

      List<Integer> res = new ArrayList<Integer>();

      if (matcherA.find()){
        String[] rawA = matcherA.group().split(",");

        for (String l : rawA){
          Matcher d = digit.matcher(l);
          d.find();
          Integer num = Integer.parseInt(d.group(0));
          res.add(num);
        }
        small.put("A", res);

      } else if (matcherB.find()){
        String[] rawB = matcherB.group().split(",");

        for (String l : rawB){
          Matcher d = digit.matcher(l);
          d.find();
          Integer num = Integer.parseInt(d.group(0));
          res.add(num);
        }
        small.put("B", res);

      } else if (prize.find()) {
        String[] rawP = prize.group().split(",");

        for (String l : rawP){
          Matcher d = digit.matcher(l);
          d.find();
          Integer num = Integer.parseInt(d.group(0));
          res.add(num);
        }
        small.put("P", res);

      } else {
        continue;
      }

      if (result.get(i) != null) {
        var temp = result.get(i);
        for (String t : small.keySet()) {
          temp.put(t, small.get(t));
        }
        result.put(i, temp);
      } else {
        result.put(i, small);
      }
      System.out.println(result.get(i).size());
      System.out.println(result.get(i).size() % 3);
      if (result.get(i).size() % 3 == 0){
        System.out.println(result);
        i++;
      }
    }

    System.out.println(result);
    return result;
  }

  public static void main(String[] args) {
  }
}
