/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import java.util.HashMap;

public class AppTest {
  @Test
  public void reaLines() {
    App classUnderTest = new App();
    assert (classUnderTest.readLines("/home/timon/projects/advent-of-code/2024/day_13/example.txt").size() > 0);
  }

  @Test
  public void parseDataFromFile(){
    App classUnderTest = new App();
    List <String> data = classUnderTest.readLines("/home/timon/projects/advent-of-code/2024/day_13/example.txt");
    var Result = classUnderTest.buildMap(data);
    assert Result.get(0) != null;
  }

  @Test
  public void tryToCalculate(){
    App classUnderTest = new App();
    List <String> data = classUnderTest.readLines("/home/timon/projects/advent-of-code/2024/day_13/example.txt");
    var Result = classUnderTest.buildMap(data);

  }
}
